{{- if .Values.createCustomResource -}}
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databases.jakub-bacic.github.com
  labels:
    app: {{ template "database-k8s-operator.name" . }}
    chart: {{ template "database-k8s-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": crd-install
spec:
  group: jakub-bacic.github.com
  names:
    kind: Database
    listKind: DatabaseList
    plural: databases
    singular: database
    {{- if .Values.databaseResourceShortNames }}
    shortNames:
      {{- range .Values.databaseResourceShortNames }}
      - {{ . | quote }}
      {{- end }}
    {{- end }}
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            database:
              properties:
                name:
                  type: string
                user:
                  type: string
                passwordSecretRef:
                  type: object
                  properties:
                    name:
                      type: string
                    key:
                      type: string
                  required:
                    - name
                    - key
              required:
                - name
                - user
                - passwordSecretRef
            databaseServer:
              type: object
              properties:
                type:
                  type: string
                host:
                  type: string
                port:
                  type: integer
                  minimum: 1
                  maximum: 65536
                rootUser:
                  type: string
                rootPasswordSecretRef:
                  type: object
                  properties:
                    name:
                      type: string
                    key:
                      type: string
                  required:
                    - name
                    - key
              required:
                - type
                - host
                - port
                - rootUser
                - rootPasswordSecretRef
          required:
            - database
            - databaseServer
  additionalPrinterColumns:
    - name: DB Type
      type: string
      description: The database server type
      JSONPath: .spec.databaseServer.type
    - name: DB Host
      type: string
      description: The database server host
      JSONPath: .spec.databaseServer.host
    - name: Status
      type: string
      description: Current database status (Creating|Created|Deleting|Error)
      JSONPath: .status.status
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp
{{- end -}}