apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "database-k8s-operator.fullname" . }}
  labels:
    app: {{ template "database-k8s-operator.name" . }}
    chart: {{ template "database-k8s-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "database-k8s-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "database-k8s-operator.name" . }}
        release: {{ .Release.Name }}
        {{- if .Values.podLabels }}
        {{ .Values.podLabels | toYaml | indent 8 | trim }}
        {{- end }}
      {{- if .Values.podAnnotations }}
      annotations:
        {{ .Values.podAnnotations | toYaml | indent 8 | trim }}
      {{- end }}
    spec:
      serviceAccountName: {{ template "database-k8s-operator.fullname" . }}
      containers:
        - name: database-k8s-operator
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
          - database-k8s-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              value: {{ .Values.watchNamespace }}
            - name: OPERATOR_NAME
              value: "database-k8s-operator"
          {{- if .Values.resources }}
          resources:
            {{ .Values.resources | toYaml | indent 12 | trim }}
          {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
        {{ .Values.nodeSelector | toYaml | indent 8 | trim }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity:
        {{ .Values.affinity | toYaml | indent 8 | trim }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
        {{ .Values.tolerations | toYaml | indent 8 | trim }}
      {{- end }}