apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: databaseservers.jakub-bacic.github.com
spec:
  group: jakub-bacic.github.com
  names:
    kind: DatabaseServer
    listKind: DatabaseServerList
    plural: databaseservers
    singular: databaseserver
    shortNames:
      - dbserver
  scope: Namespaced
  version: v1alpha1
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            type:
              type: string
            host:
              type: string
            port:
              type: integer
              minimum: 1
              maximum: 65536
            rootUser:
              type: string
            rootUserSecretRef:
              type: object
              properties:
                name:
                  type: string
                key:
                  type: string
              required:
                - name
                - key
          required:
            - type
            - host
            - port
            - rootUser
            - rootUserSecretRef
  additionalPrinterColumns:
    - name: Type
      type: string
      description: The database server type
      JSONPath: .spec.type
    - name: Age
      type: date
      JSONPath: .metadata.creationTimestamp